### ISSUE TITLE
Value error

### ISSUE THREAD

**Issue by vincespice** [DenizShabani/telegramscraper#10]
Hello. When I run scraper.py, i get value error, after enter choice. I try public group name, private group link, but not working. Can you help me?

(~) Choose an account to scrape members

(0) +3630768621

(~) Enter choice: 0
Enter the name of the group without the @: https://t.me/+8yebeAUk3mFjNmFk
Traceback (most recent call last):
  File "C:\Users\spice\PycharmProjects\telegramscraper\scraper.py", line 79, in <module>
    group = c.get_entity(group_name)
  File "C:\Users\spice\AppData\Local\Programs\Python\Python39\lib\site-packages\telethon\sync.py", line 39, in syncified
    return loop.run_until_complete(coro)
  File "C:\Users\spice\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "C:\Users\spice\AppData\Local\Programs\Python\Python39\lib\site-packages\telethon\client\users.py", line 335, in get_entity
    result.append(await self._get_entity_from_string(x))
  File "C:\Users\spice\AppData\Local\Programs\Python\Python39\lib\site-packages\telethon\client\users.py", line 574, in _get_entity_from_string
    raise ValueError(
ValueError: Cannot find any entity corresponding to "https://t.me/+8yebeAUk3mFjNmFk"

Process finished with exit code 1

**Comment by moumen100** [comment]
remove http:// 
use only [t.me/+8yebeAUk3mFjNmFk](https://t.me/+8yebeAUk3mFjNmFk)
