### ISSUE TITLE
help urgent 

### ISSUE THREAD

**Issue by knmzz** [DenizShabani/telegramscraper#11]
Traceback (most recent call last):
  File "C:\Users\Arda\Desktop\telegramscraper-main\scraper.py", line 115, in <module>
    for member in c.iter_participants(group, filter=ChannelParticipantsAdmins):

**Comment by ChankitSaini** [comment]
> scraper.py members made such an error when registering in the file
> 
> Traceback (most recent call last): File "C:\Users\Arda\Desktop\telegramscraper-main\scraper.py", line 115, in for member in c.iter_participants(group, filter=ChannelParticipantsAdmins):

Please share full logs, use a pastebin service to share logs, or share a image screenshot of the same. 

Pastebin: pastebin.com

**Comment by rahilalbert** [comment]
Traceback (most recent call last):
  File "C:\Users\Lenovo\Desktop\telegramscraper-main\telegramscraper-main\manager.py", line 1, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

**Comment by ChankitSaini** [comment]
> 

Do `pip install requests` in terminal.
