### ISSUE TITLE
Missing module

### ISSUE THREAD

**Issue by rahilalbert** [DenizShabani/telegramscraper#21]
Traceback (most recent call last):
  File "C:\Users\Lenovo\Desktop\telegramscraper-main\telegramscraper-main\manager.py", line 1, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

**Comment by rahilalbert** [comment]
Issue for python scraper.py 

Traceback (most recent call last):
  File "C:\Users\Lenovo\Desktop\telegramscraper-main\telegramscraper-main\scraper.py", line 50, in <module>
    f = open('vars.txt', 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'vars.txt'

**Comment by rahilalbert** [comment]
Issue for  python tsadder.py

Traceback (most recent call last):
  File "C:\Users\Lenovo\Desktop\telegramscraper-main\telegramscraper-main\tsadder.py", line 73, in <module>
    f = open('vars.txt', 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'vars.txt'

**Comment by rahilalbert** [comment]
I had to pip install requests
